<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationManifest Condition="Exists('app.manifest')">app.manifest</ApplicationManifest>
    <AssemblyName>DesktopFloatingLauncher</AssemblyName>
    <RootNamespace>FloatingLauncher</RootNamespace>
    <StartupObject>FloatingLauncher.Program</StartupObject>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Xaml" />
    <Reference Include="WindowsBase" />
    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Data" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>

</Project>
